version: '3'
services:
  host:
    build: .  
    entrypoint: /bin/bash
    stdin_open: true
    tty: true  
    networks:
      static-network:
        ipv4_address: 172.16.238.10
 
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.16.238.0/24
        
        
